baseline: {}

tau_legacy:
  tau: 5
tau_low:
  tau: 8
tau_high:
  tau: 12

kappa_low:
  kappa: 350
kappa_high:
  kappa: 450

delta_low:
  delta_range: [55, 95]
delta_high:
  delta_range: [90, 160]

edge_soft:
  sigma2_edge_range: [1.0, 1.6]
edge_strong:
  sigma2_edge_range: [1.4, 2.2]